name: flutter_application_smartshop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
    - assets/files/
    - assets/images/facebookicon.png
    - assets/images/googleicon.png
